config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'main#index'

  devise_for :users

  resources :users, only: [:new, :create] do
    resources :tasks, only: [:index, :show, :new]
  end
  
  resources :projects do 
    resources :tasks, only: [:new]
  end
  
  resources :tasks

  get '/tasks/:id/complete', to: "tasks#complete"
  delete '/tasks/:id', to: "tasks#destroy"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  #  active admin
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "username","encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    # validates :projectname, presence :true
    has_many :tasks
    has_many :users, through: :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    validates :submittedto,presence: true
    belongs_to :user
    belongs_to :project

  # Set the default value for 'completed' attribute
  attribute :completed, :boolean, default: false

  # Validate that 'completed' is either true or false
  validates :completed, inclusion: { in: [true, false] }

  # active admin
  def self.ransackable_attributes(auth_object = nil)
    ["assignedto", "completed", "created_at", "id", "project_id", "submittedon", "submittedto", "updated_at", "user_id"]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  has_many :projects, through: :tasks

  enum role: [:user, :manager]

  # add default role when newly user created!
  before_save do
    self.role = :user unless ['manager'].include?(self.role)
  end

  # display the user in the new task
  def full_name_with_role
    "#{username} (#{role})"
  end

  # active admin
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email","username", "role", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["projects", "tasks"]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!

    # def authorized
    #     current_user.id == @task.user_id || (current_user.role == 'manager' || current_user.role == 'admin')
    # end

    def authorized
      current_user.id == @task.user_id || current_user.role.in?(['manager', 'admin']) && current_user.projects.include?(@task.project)
    end
    
    helper_method :authorized


  protected

    def configure_permitted_parameters
      # for adding a paramater to create 
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])

      # for adding a paramater to update to solve unpermitted_parameter issue 
      added_attrs = [:username, :role, :password, :password_confirmation, :current_password]
      devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if user_signed_in?
      redirect_to projects_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit,:update, :destroy]
    def index
        @projects = Project.all
    end

    def show
        @tasks = @project.tasks
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            redirect_to projects_path
        else
        render :new
        end
    end

    def edit    
    end

    def update
        if @project.update(project_params)
            redirect_to projects_path
        else
            render :edit
        end
    end

     def destroy
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to projects_path
    end

    private

    def set_project
        @project = Project.find(params[:id])
    end

    def project_params
        params.require('project').permit(:projectname)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:edit, :update, :destroy, :complete]

    def index
        if params[:user_id]
            if User.find(params[:user_id])== current_user
                @user = User.find(params[:user_id])
                @tasks = @user.tasks
            else
                redirect_to projects_path
                flash[:notice] = "Unauthorized Access."
            end
        else
            @tasks = Task.all
        end
    end

    def new
        if params[:user_id]
            @user = User.find(params[:user_id])
            @task = @user.tasks.build
            @task = Task.new(user_id: @user.id)
        elsif params[:project_id]
            @project = Project.find(params[:project_id])
            @task = Task.new(project_id: @project.id)
        else
            @user = nil
            @task = Task.new
        end
    end

    def create
        @task = Task.new(task_params)
        # Find the user by user_id and set the username as assignedto
        user = User.find(params[:task][:user_id])
        @task.assignedto = user.username
        if @task.save
            redirect_to projects_path
        else
            render :new
        end
    end
    
    def edit
        if authorized
        else 
            redirect_to projects_path
            flash[:notice] = "You can only make changes to your Tasks."
        end
    end

    def update
        if @task.update(task_params)
            user = User.find(params[:task][:user_id])
            @task.assignedto = user.username
            redirect_to projects_path
        else
            render :edit
        end
    end
    
    def complete
        if authorized
            @task.update(completed: true)
            redirect_to projects_path
        else
            redirect_to projects_path
            flash[:notice] = "You can only complete your projects."
        end
    end

     def destroy
        if authorized
            @task.destroy
            redirect_to projects_path
        else
            redirect_to projects_path
            flash[:notice] = "You can only delete your own tasks."
        end
    end

    private

    def set_task
        @task = Task.find(params[:id])
    end

    def task_params
        params.require(:task).permit(:assignedto, :submittedto, :user_id, :project_id, :status, :submittedon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<% if user_signed_in? %>
    <%= button_to "Log Out",destroy_user_session_path,method: :delete,class:"btn btn-secondary"%>
    <%= link_to "Edit",edit_user_registration_path,class:"btn btn-secondary"%>

<% else%>
    <%= button_to "Log in",new_user_session_path,class:"btn btn-primary"%>
    <%= link_to "Registration",new_user_registration_path,class:"btn btn-primary"%>
<% end %>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
        <%= pluralize(@project.errors.count, "error") %>
        This post did could not be saved:
        </h2>

        <ul>
        <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <%= form_for @project do |f| %>
        <%= f.label :projectname, "Name" %>
        <%= f.text_field :projectname %>
        <%= f.submit "Create", class: "btn btn-primary" %>

<% end  %>

app/views/projects/edit.html.erb
<%= render 'projects/form'%>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%# <a href="/users/most_projects"> Click here to see who has the most projects!</a> %>
    <% @projects.all.each do |project| %>
        <div class="container">

        <h2>  <%= link_to "#{project.projectname}", project_path(project)%></h2>

        <% tasks = project.tasks %>

        <%= render partial: 'tasks/tasklist', :locals => {:@tasks => tasks}%>
        </div>
<% end  %>
<%= link_to"Create new Project",new_project_path%>
<%# <%= link_to"new_project_task",edit_project_path%>

app/views/projects/new.html.erb
<div class="container">
<br>
    <div class="center-block">
        <%= render 'projects/form', :locals => {:@project => @project} %>
    </div>
</div>

app/views/projects/show.html.erb
<h1>
<%= @project.projectname %> 
</h1>

<p> <%= link_to "Add task to project", new_project_task_url(@project) %></p>

<% if @tasks.present? && current_user.id == @tasks[0].user_id %>
    <%= link_to "Edit Project", edit_project_path(@project) %>
    <%=   link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure?' } %> 
<% end %>
<% tasks = @project.tasks %>
<%= render partial: 'tasks/tasklist', :locals => {:@tasks => tasks}%>

app/views/shared/_flash.html.erb
<% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %> 
<% if alert %> <p class="alert alert-danger"><%= alert %></p> <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to "Project Management",projects_path,class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <% if current_user && current_user.role=="manager" %>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_task_path %>">New Task</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= new_project_path %>">New Project</a>
      </li>
    <% end %>
      <li class="nav-item">
      <% if user_signed_in? %>
        <a class="nav-link" href="<%=user_tasks_path(current_user) %>">My Tasks</a>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/tasks">All Tasks</a>
      </li>
      <li>
      <% if user_signed_in? %>
        <%= button_to "Log Out",destroy_user_session_path,method: :delete,class:"nav-link"%>
      </li>
      <li>
        <%= link_to "Edit Registration",edit_user_registration_path,class:"nav-link"%>
      </li>
     <% else %>
      <li>
        <%= button_to "Log in",new_user_session_path,class:"nav-link"%>
      </li>
        <%= link_to "Register Here",new_user_registration_path,class:"nav-link"%>
     <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/tasks/_completed.html.erb
<table style="width:100%">
<tr>
    <th>Project</th>
    <th>Assigned To</th>      
    <th>Submitted on</th>
    <th>Submitted To</th>
    <%if current_user && current_user.role == "manager" %>
    <th>Delete</th>
    <% end %>
    <th>Complete</th>
    <th>Event Status</th>
</tr>

<% @tasks.all.each do |task| %>
<% if task.completed %>
    <tr>
        <td><%= task.project.projectname %></td>
        <td> <%= task.user.username  %> </td>
        <td> <%= task.submittedon.strftime("%B %d, %Y") unless task.submittedon.nil?%></td>
        <td> <%= task.submittedto  %> </td>
        <%if current_user && current_user.role == "manager" %>
            <td> <%=  button_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }  %> </td>
        <% end %>       
        <td class="text-success"> Completed </td>
        <% if Date.current <= task.submittedon %>
        <td style="color: green; font-weight: bold;">ON TIME</td
        <% else %>
        <td style="color: red;
        font-weight: bold;">LATE</td>
        <% end %>
    </tr>
    <% end %>

<% end  %>

</table>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2>
      <%= pluralize(@task.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div class="card-body">
          <h2 class="card-title text-center mb-4">New Task</h2>

          <%= form_for(@task, html: { class: "form" }) do |f| %>
            <div class="form-group">
              <%= f.label :submittedto, "Submitted To" %>
              <%= f.collection_select :submittedto, User.where(role: ['manager','admin']), :username, :full_name_with_role, { prompt: 'Select a user' }, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :submittedon, "Submitted On" %>
              <%= f.date_select :submittedon, { class: "form-control" } %>
            </div>

            <% if @project %>
              <%= f.hidden_field :project_id %>
            <% else  %>
              <div class="form-group">
                <%= f.label :project_id, "Select the Project for this task:" %><br>
                <%= f.collection_select :project_id, Project.all, :id, :projectname, { prompt: 'Select a project' }, class: 'form-control' %>
              </div>
            <% end %>

            <% if @user %>
              <%= f.hidden_field :user_id  %>
            <% else  %>
              <div class="form-group">
                <%= f.label :user_id, "Select the User for this task:" %><br>
                <%= f.collection_select :user_id, User.all, :id, :username, { prompt: 'Select a user' }, class: 'form-control' %>
              </div>
            <% end %>

            <div class="form-group text-center">
              <%= f.submit "Submit", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_tasklist.html.erb
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Project</th>
      <th scope="col">Assigned To</th>
      <th scope="col">Submitted To</th>
      <% if current_user && current_user.role == "manager" %>
        <th scope="col">Edit/Delete</th>
      <% end %>
      <th scope="col">Complete</th>
    </tr>
  </thead>
  <tbody>
    <% if current_user && current_user.role == "user" %>
      <% @tasks.all.each do |task| %>
        <% if !task.completed %>
          <tr scope="row">
            <td><%= task.project.projectname %></td>
            <td><%= task.user.username %></td>
            <td><%= task.submittedto %></td>
            <td><a class="btn btn-outline-success" href="/tasks/<%= task.id %>/complete">Complete</a></td>
          </tr>
        <% end %>
      <% end %>
    <% elsif current_user && current_user.role == "manager" %>
      <% @tasks.each do |task| %>
        <% if !task.completed %>
          <tr scope="row">
            <td><%= task.project.projectname %></td>
            <td><%= task.user.username %></td>
            <td><%= task.submittedto %></td>
            <% if current_user && current_user.role == "manager" %>
              <td>
                <%= link_to "Edit", edit_task_path(task) %> /
                <%= button_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            <% end %>
            <td><a class="btn btn-outline-success" href="/tasks/<%= task.id %>/complete">Complete</a></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<%= render 'form',  :locals => {:@task => @task} %>

app/views/tasks/index.html.erb
<% if @user %>
<div class="container">
    <h1>Welcome, <%= @user.username if @user%>  </h1><br>
    <h2>Here are your tasks:</h2><br>
    <%= link_to "Give yourself a new task!", new_user_task_path(@user) %>
    <br><br>
</div>
<% end  %>

    <%= render 'tasklist', :locals => {:@tasks => @tasks} %>

<br><br>

<h2>Completed Tasks</h2>

<%= render 'completed', :locals => {:@tasks => @tasks} %>

app/views/tasks/new.html.erb
<%= render 'tasks/form',  :locals => {:@task => @task} %>